### ISSUE TITLE
Not an issue, just an educational question

### ISSUE THREAD

**Issue by vandidant** [magnusvk/FlickrFaves#3]
Hi, first I'd like to thank you for this software, it is very very very useful :)

I'm very newb when it comes to programming, with nothing more than high-school Java skills. I'm curious about how the program gets the original url, so looking through your source code I see this, but I wasn't able to find its Declaration.

				String originalUrl = null;
				try {
					originalUrl = curPhoto.getOriginalUrl();
				} catch (FlickrException e) {
					// if the original url just isn't available, fine. no need
					// to panic.
				}

I'm using Netbeans right now and it's not finding anything when I click on any of the Navigate>Go To buttons on curPhoto. I'd imagine there's an easy way to find the code that it's referring to, but I don't really know what to search on google to learn how to do it. If you're not busy at this moment, could you please tell me where it is and how I should be finding it on my own?

Thanks for your time.

**Comment by magnusvk** [comment]
Just seeing this! That method comes from [this included library](https://github.com/magnusvk/FlickrFaves/blob/master/lib/flickrapi-1.2.jar).
