### ISSUE TITLE
Downloads limited to 1024px

### ISSUE THREAD

**Issue by kilrah** [magnusvk/FlickrFaves#4]
Since a few days it seems FlickrFaves will only download the 1024px version of images from people who disabled original file downloads, even if they are available in higher resolution and can be viewed as such on the site.

Any idea how to fix?

**Comment by magnusvk** [comment]
Could you post the link to an image this is happening with? I can't immediately reproduce this.

**Comment by kilrah** [comment]
This is one I did my tests on to confirm before posting: https://www.flickr.com/photos/85464137@N00/26838947056/in/faves-61800162@N05/

If it matters, I have a **large** number of faves, around 19200. Could be that it started failing while crossing some number... 
I'll try downloading in a new folder with a size filter to see if it changes something.

**Comment by kilrah** [comment]
OK, after some investigation, there's a combination of things:
 
- It seems the "original" is no more accessible if the owner has disabled downloads. Could be a change on Flickr side in the API in the way those are retrieved, or they disabled access completely...
- As seen in https://github.com/magnusvk/FlickrFaves/blob/master/src/de/vonkoeller/flickrFaves/api/Favorites.java#L130 it seems the next fallback is the "b" size which is 1024, while there are now (and have been for several years) a "k" size (2048) and "h" size (1600) that would be preferable instead. It seems the flickrapi-1.2 library may need modification to add support for those in addition to FlickrFaves.

Besides that during testing I found that the size limit doesn't always work, but that'll deserve a separate issue...
